Repository capstone-mindmate/mindmate-backend, pull requests merged in 2025-04, with the labels that each got.

#36 [Feat#35] 신고 기능
  src/main/java/com/mindmate/mindmate_server/auth/util/JwtTokenProvider.java
  src/main/java/com/mindmate/mindmate_server/chat/controller/WebSocketChatController.java
  src/main/java/com/mindmate/mindmate_server/global/config/SecurityConfig.java
  src/main/java/com/mindmate/mindmate_server/global/exception/ReportErrorCode.java
  src/main/java/com/mindmate/mindmate_server/matching/service/MatchingService.java
  src/main/java/com/mindmate/mindmate_server/matching/service/MatchingServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/report/controller/AdminReportController.java
  src/main/java/com/mindmate/mindmate_server/report/controller/ReportController.java
  src/main/java/com/mindmate/mindmate_server/report/domain/Report.java
  src/main/java/com/mindmate/mindmate_server/report/domain/ReportReason.java
  src/main/java/com/mindmate/mindmate_server/report/domain/ReportTarget.java
  src/main/java/com/mindmate/mindmate_server/report/dto/ReportDetailResponse.java
  src/main/java/com/mindmate/mindmate_server/report/dto/ReportRequest.java
  src/main/java/com/mindmate/mindmate_server/report/dto/ReportResponse.java
  src/main/java/com/mindmate/mindmate_server/report/dto/ReportStatisticsResponse.java
  src/main/java/com/mindmate/mindmate_server/report/dto/SuspensionRequest.java
  src/main/java/com/mindmate/mindmate_server/report/dto/UnsuspendRequest.java
  src/main/java/com/mindmate/mindmate_server/report/repository/ReportRepository.java
  src/main/java/com/mindmate/mindmate_server/report/repository/ReportRepositoryCustom.java
  src/main/java/com/mindmate/mindmate_server/report/repository/ReportRepositoryImpl.java
  src/main/java/com/mindmate/mindmate_server/report/service/AdminReportService.java
  src/main/java/com/mindmate/mindmate_server/report/service/AdminServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/report/service/ReportService.java
  src/main/java/com/mindmate/mindmate_server/report/service/ReportServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/report/util/SuspensionScheduler.java
  src/main/java/com/mindmate/mindmate_server/user/domain/RoleType.java
  src/main/java/com/mindmate/mindmate_server/user/domain/User.java
  src/main/java/com/mindmate/mindmate_server/user/repository/UserRepository.java
  src/main/java/com/mindmate/mindmate_server/user/service/UserService.java
  src/main/java/com/mindmate/mindmate_server/user/service/UserServiceImpl.java
Labels: feat

#39 [Feat#38] 신고 테스트 코드
  src/main/java/com/mindmate/mindmate_server/global/config/SecurityConfig.java
  src/main/java/com/mindmate/mindmate_server/report/dto/ReportRequest.java
  src/main/java/com/mindmate/mindmate_server/report/dto/UnsuspendRequest.java
  src/main/java/com/mindmate/mindmate_server/report/service/AdminReportServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/user/domain/RoleType.java
  src/test/java/com/mindmate/mindmate_server/profile/service/ProfileServiceTest.java
  src/test/java/com/mindmate/mindmate_server/report/service/AdminReportServiceImplTest.java
  src/test/java/com/mindmate/mindmate_server/report/service/ReportServiceImplTest.java
Labels: test

#44 [Test#42] 매칭 테스트
  src/main/java/com/mindmate/mindmate_server/matching/controller/MatchingController.java
  src/main/java/com/mindmate/mindmate_server/matching/domain/Matching.java
  src/main/java/com/mindmate/mindmate_server/matching/dto/MatchingCreateRequest.java
  src/main/java/com/mindmate/mindmate_server/matching/dto/MatchingDetailResponse.java
  src/main/java/com/mindmate/mindmate_server/matching/dto/MatchingUpdateRequest.java
  src/main/java/com/mindmate/mindmate_server/matching/dto/WaitingUserResponse.java
  src/main/java/com/mindmate/mindmate_server/matching/repository/MatchingRepository.java
  src/main/java/com/mindmate/mindmate_server/matching/repository/MatchingRepositoryCustom.java
  src/main/java/com/mindmate/mindmate_server/matching/repository/MatchingRepositoryImpl.java
  src/main/java/com/mindmate/mindmate_server/matching/repository/WaitingUserRepository.java
  src/main/java/com/mindmate/mindmate_server/matching/service/MatchingEventConsumer.java
  src/main/java/com/mindmate/mindmate_server/matching/service/MatchingService.java
  src/main/java/com/mindmate/mindmate_server/matching/service/MatchingServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/matching/service/RedisMatchingService.java
  src/test/java/com/mindmate/mindmate_server/matching/service/MatchingEventConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/matching/service/MatchingEventProducerTest.java
  src/test/java/com/mindmate/mindmate_server/matching/service/MatchingServiceImplTest.java
  src/test/java/com/mindmate/mindmate_server/matching/service/RedisMatchingServiceTest.java
Labels: update, test

#43 [Feat#40] 채팅 redis 로직 수정 및 리팩토링
  src/main/java/com/mindmate/mindmate_server/chat/controller/WebSocketChatController.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/ChatEvent.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/ChatEventType.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/PresenceRequest.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/ReactionRequest.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ChatEventPublisher.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ChatPresenceService.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ChatServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/chat/util/ChatMessageListener.java
  src/main/java/com/mindmate/mindmate_server/chat/util/WebSocketDestinationResolver.java
  src/main/java/com/mindmate/mindmate_server/global/config/SecurityConfig.java
  src/main/resources/templates/websocket-test.html
Labels: update, refact

#53 [Feat#45] 매거진 기능 설계
  src/main/java/com/mindmate/mindmate_server/global/exception/MagazineErrorCode.java
  src/main/java/com/mindmate/mindmate_server/magazine/controller/AdminMagazineController.java
  src/main/java/com/mindmate/mindmate_server/magazine/controller/MagazineController.java
  src/main/java/com/mindmate/mindmate_server/magazine/domain/Magazine.java
  src/main/java/com/mindmate/mindmate_server/magazine/domain/MagazineImage.java
  src/main/java/com/mindmate/mindmate_server/magazine/domain/MagazineLike.java
  src/main/java/com/mindmate/mindmate_server/magazine/domain/MagazineStatus.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineCategoryStatistics.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineCreateRequest.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineDetailResponse.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineResponse.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineSearchFilter.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineUpdateRequest.java
  src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineRepository.java
  src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineRepositoryCustom.java
  src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineRepositoryImpl.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineService.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineStatisticsService.java
  src/main/java/com/mindmate/mindmate_server/user/domain/User.java
Labels: feat

#56 [Feat#52] 매거진 좋아요, 이미지 관리
  build.gradle
  libs/webp-imageio-core-0.1.3.jar
  src/main/java/com/mindmate/mindmate_server/global/config/WebMvcConfig.java
  src/main/java/com/mindmate/mindmate_server/global/exception/MagazineErrorCode.java
  src/main/java/com/mindmate/mindmate_server/magazine/controller/MagazineController.java
  src/main/java/com/mindmate/mindmate_server/magazine/controller/MagazineImageController.java
  src/main/java/com/mindmate/mindmate_server/magazine/domain/Magazine.java
  src/main/java/com/mindmate/mindmate_server/magazine/domain/MagazineImage.java
  src/main/java/com/mindmate/mindmate_server/magazine/domain/MagazineLike.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/ImageResponse.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/LikeResponse.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineCreateRequest.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineDetailResponse.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineResponse.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineUpdateRequest.java
  src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineImageRepository.java
  src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineLikeRepository.java
  src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineRepository.java
  src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineRepositoryImpl.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineImageService.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineService.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/magazine/util/MagazineImageCleanUpScheduler.java
Labels: feat

#58 [Test#55] 매거진 테스트
  .gitignore
  src/main/java/com/mindmate/mindmate_server/magazine/domain/Magazine.java
  src/main/java/com/mindmate/mindmate_server/magazine/domain/MagazineImage.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineCreateRequest.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineImageService.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImpl.java
  src/test/java/com/mindmate/mindmate_server/chat/service/ChatPresenceServiceTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/ChatServiceTest.java
  src/test/java/com/mindmate/mindmate_server/magazine/MagazineImageServiceIntegrationTest.java
  src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineImageServiceTest.java
  src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImplTest.java
  src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineStatisticsServiceTest.java
Labels: test

#64 [Update, Test#63] 알림 서비스 및 테스트 수정
  src/main/java/com/mindmate/mindmate_server/global/config/KafkaConfig.java
  src/main/java/com/mindmate/mindmate_server/notification/service/NotificationConsumer.java
  src/main/java/com/mindmate/mindmate_server/notification/service/NotificationProducer.java
  src/main/java/com/mindmate/mindmate_server/notification/service/NotificationService.java
  src/test/java/com/mindmate/mindmate_server/notification/service/NotificationConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/notification/service/NotificationProducerTest.java
  src/test/java/com/mindmate/mindmate_server/notification/service/NotificationServiceTest.java
Labels: update, test

#68 [Feat#66] 채팅 필터링, 토스트 박스 처리
  src/main/java/com/mindmate/mindmate_server/chat/controller/FilteringWordController.java
  src/main/java/com/mindmate/mindmate_server/chat/controller/ToastBoxController.java
  src/main/java/com/mindmate/mindmate_server/chat/domain/FilteringWord.java
  src/main/java/com/mindmate/mindmate_server/chat/domain/FilteringWordCategory.java
  src/main/java/com/mindmate/mindmate_server/chat/domain/ToastBoxKeyword.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/ChatEventType.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/ChatMessageEvent.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/FilteringWordDTO.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/FilteringWordRequest.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/ToastBoxEvent.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/ToastBoxKeywordDTO.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/ToastBoxKeywordRequest.java
  src/main/java/com/mindmate/mindmate_server/chat/repository/FilteringWordRepository.java
  src/main/java/com/mindmate/mindmate_server/chat/repository/ToastBoxRepository.java
  src/main/java/com/mindmate/mindmate_server/chat/service/AhoCorasickMatcher.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ChatServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ContentFilterConsumer.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ContentFilterService.java
  src/main/java/com/mindmate/mindmate_server/chat/service/FilteringWordService.java
  src/main/java/com/mindmate/mindmate_server/chat/service/MessageStorageConsumer.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ToastBoxConsumer.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ToastBoxService.java
  src/main/java/com/mindmate/mindmate_server/global/config/MatcherConfig.java
  src/main/java/com/mindmate/mindmate_server/global/exception/FilteringErrorCode.java
  src/main/resources/templates/websocket-test.html
Labels: feat

#72 [Refact#69] 채팅 로직 리팩토
  src/main/java/com/mindmate/mindmate_server/chat/controller/ChatController.java
  src/main/java/com/mindmate/mindmate_server/chat/controller/CustomFormController.java
  src/main/java/com/mindmate/mindmate_server/chat/domain/ChatMessage.java
  src/main/java/com/mindmate/mindmate_server/chat/domain/ChatRoom.java
  src/main/java/com/mindmate/mindmate_server/chat/domain/FilteringWordCategory.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/ChatMessageResponse.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/MessageReactionResponse.java
  src/main/java/com/mindmate/mindmate_server/chat/service/AhoCorasickMatcher.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ChatMessageServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ChatSearchService.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ChatServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ContentFilterService.java
  src/main/java/com/mindmate/mindmate_server/chat/service/CustomFormService.java
  src/main/java/com/mindmate/mindmate_server/chat/service/CustomFormServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/chat/service/FilteringWordService.java
  src/main/java/com/mindmate/mindmate_server/chat/service/FilteringWordServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/chat/service/MessageEncryptConsumer.java
  src/main/java/com/mindmate/mindmate_server/chat/service/MessageReactionService.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ToastBoxService.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ToastBoxServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/chat/service/UnreadCountConsumer.java
  src/main/java/com/mindmate/mindmate_server/chat/util/ChatMessageListener.java
  src/main/java/com/mindmate/mindmate_server/chat/util/FilteringWordAdapter.java
  src/main/java/com/mindmate/mindmate_server/chat/util/ToastBoxAdapter.java
  src/main/java/com/mindmate/mindmate_server/global/config/MatcherConfig.java
Labels: update, refact

#74 [Feat#70] 채팅 필터링 추가 처리
  src/main/java/com/mindmate/mindmate_server/chat/controller/AdminFilteringController.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/FilteredContentDTO.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/UserFilteringHistoryDTO.java
  src/main/java/com/mindmate/mindmate_server/chat/service/AdminFilteringService.java
  src/main/java/com/mindmate/mindmate_server/chat/service/FilteringEventConsumer.java
  src/main/java/com/mindmate/mindmate_server/global/config/RedisConfig.java
  src/main/java/com/mindmate/mindmate_server/global/config/WebConfig.java
  src/main/java/com/mindmate/mindmate_server/global/exception/UserErrorCode.java
  src/main/java/com/mindmate/mindmate_server/global/util/RedisKeyManager.java
  src/main/java/com/mindmate/mindmate_server/global/util/SlackNotifier.java
  src/main/java/com/mindmate/mindmate_server/global/util/SuspensionExpirationListener.java
  src/main/java/com/mindmate/mindmate_server/report/controller/AdminReportController.java
  src/main/java/com/mindmate/mindmate_server/report/dto/SuspensionRequest.java
  src/main/java/com/mindmate/mindmate_server/report/service/AdminReportService.java
  src/main/java/com/mindmate/mindmate_server/report/service/AdminReportServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/report/service/ReportServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/report/util/SuspensionScheduler.java
  src/main/java/com/mindmate/mindmate_server/user/controller/AdminUserSuspensionController.java
  src/main/java/com/mindmate/mindmate_server/user/dto/SuspendedUserDTO.java
  src/main/java/com/mindmate/mindmate_server/user/service/AdminUserSuspensionService.java
  src/test/java/com/mindmate/mindmate_server/report/service/AdminReportServiceImplTest.java
Labels: feat

#83 [Test#76] 포인트 시스템 테스트
  src/main/java/com/mindmate/mindmate_server/point/dto/PointAddRequest.java
  src/main/java/com/mindmate/mindmate_server/point/dto/PointRequest.java
  src/main/java/com/mindmate/mindmate_server/point/dto/PointUseRequest.java
  src/main/java/com/mindmate/mindmate_server/point/service/PointServiceImpl.java
  src/test/java/com/mindmate/mindmate_server/point/service/PointServiceImplTest.java
Labels: refact, test

#79 [Feat#71] 인기 매거진 선정
  src/main/java/com/mindmate/mindmate_server/global/config/KafkaConfig.java
  src/main/java/com/mindmate/mindmate_server/global/util/RedisKeyManager.java
  src/main/java/com/mindmate/mindmate_server/global/util/SlackNotifier.java
  src/main/java/com/mindmate/mindmate_server/magazine/controller/MagazineController.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineEngagementEvent.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineEngagementRequest.java
  src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineRepository.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineEngagementConsumer.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazinePopularityService.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazinePopularityServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineService.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/magazine/util/MagazineDataCleanUpScheduler.java
  src/main/java/com/mindmate/mindmate_server/magazine/util/MagazinePopularityDecayScheduler.java
  src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImplTest.java
Labels: feat

#88 [Feat#62] 이모티콘 관리
  src/main/java/com/mindmate/mindmate_server/emoticon/controller/AdminEmoticonController.java
  src/main/java/com/mindmate/mindmate_server/emoticon/controller/EmoticonController.java
  src/main/java/com/mindmate/mindmate_server/emoticon/domain/Emoticon.java
  src/main/java/com/mindmate/mindmate_server/emoticon/domain/EmoticonStatus.java
  src/main/java/com/mindmate/mindmate_server/emoticon/domain/EmoticonType.java
  src/main/java/com/mindmate/mindmate_server/emoticon/domain/UserEmoticon.java
  src/main/java/com/mindmate/mindmate_server/emoticon/dto/EmoticonAdminResponse.java
  src/main/java/com/mindmate/mindmate_server/emoticon/dto/EmoticonDetailResponse.java
  src/main/java/com/mindmate/mindmate_server/emoticon/dto/EmoticonNotificationEvent.java
  src/main/java/com/mindmate/mindmate_server/emoticon/dto/EmoticonResponse.java
  src/main/java/com/mindmate/mindmate_server/emoticon/dto/EmoticonUploadRequest.java
  src/main/java/com/mindmate/mindmate_server/emoticon/dto/UserEmoticonResponse.java
  src/main/java/com/mindmate/mindmate_server/emoticon/repository/EmoticonRepository.java
  src/main/java/com/mindmate/mindmate_server/emoticon/repository/UserEmoticonRepository.java
  src/main/java/com/mindmate/mindmate_server/emoticon/service/AdminEmoticonService.java
  src/main/java/com/mindmate/mindmate_server/emoticon/service/EmoticonService.java
  src/main/java/com/mindmate/mindmate_server/emoticon/service/EmoticonServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/global/config/WebMvcConfig.java
  src/main/java/com/mindmate/mindmate_server/global/exception/EmoticonErrorCode.java
  src/main/java/com/mindmate/mindmate_server/global/util/SlackNotifier.java
  src/main/java/com/mindmate/mindmate_server/notification/domain/NotificationType.java
  src/main/java/com/mindmate/mindmate_server/user/domain/User.java
Labels: feat

#91 [Feat#82] 이모티콘 리팩토링 및 테스트 코드
  src/main/java/com/mindmate/mindmate_server/auth/service/AuthServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/chat/controller/ChatController.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/ChatRoomNotificationEvent.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ChatServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/emoticon/service/AdminEmoticonService.java
  src/main/java/com/mindmate/mindmate_server/emoticon/service/EmoticonService.java
  src/main/java/com/mindmate/mindmate_server/emoticon/service/EmoticonServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/global/dto/FileInfo.java
  src/main/java/com/mindmate/mindmate_server/global/exception/CommonErrorCode.java
  src/main/java/com/mindmate/mindmate_server/global/service/FileStorageService.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineImageService.java
  src/test/java/com/mindmate/mindmate_server/emoticon/service/AdminEmoticonServiceTest.java
  src/test/java/com/mindmate/mindmate_server/emoticon/service/EmoticonServiceTest.java
Labels: refact, test

#92 [Test#86] 채팅 관련 테스트 코드
  src/main/java/com/mindmate/mindmate_server/chat/service/ResponseTimeCalculationConsumer.java
  src/test/java/com/mindmate/mindmate_server/chat/service/AdminFilteringServiceTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/AesGcmEncryptionServiceTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/AhoCorasickMatcherTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/ChatNotificationConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/ChatRoomCloseNotificationConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/ChatRoomServiceTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/ChatServiceTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/ContentFilterServiceTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/CustomFormServiceTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/FilteringEventConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/FilteringWordServiceImplTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/MessageEncryptConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/ResponseTimeCalculationConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/ToastBoxConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/ToastBoxServiceImplTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/UnreadConsumerTest.java
Labels: test

#95 [Feat#80] 채팅, 매거진에서 이모티콘 사용
  src/main/java/com/mindmate/mindmate_server/chat/controller/WebSocketChatController.java
  src/main/java/com/mindmate/mindmate_server/chat/domain/ChatMessage.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/ChatEventType.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/ChatMessageEvent.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/ChatMessageResponse.java
  src/main/java/com/mindmate/mindmate_server/chat/service/CustomFormServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ToastBoxConsumer.java
  src/main/java/com/mindmate/mindmate_server/chat/util/WebSocketDestinationResolver.java
  src/main/java/com/mindmate/mindmate_server/emoticon/dto/EmoticonMessageRequest.java
  src/main/java/com/mindmate/mindmate_server/emoticon/dto/EmoticonMessageResponse.java
  src/main/java/com/mindmate/mindmate_server/emoticon/service/EmoticonService.java
  src/main/java/com/mindmate/mindmate_server/emoticon/service/EmoticonServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/global/config/SecurityConfig.java
  src/main/java/com/mindmate/mindmate_server/global/config/WebMvcConfig.java
  src/main/java/com/mindmate/mindmate_server/global/exception/EmoticonErrorCode.java
  src/main/java/com/mindmate/mindmate_server/magazine/domain/Magazine.java
  src/main/java/com/mindmate/mindmate_server/magazine/domain/MagazineContent.java
  src/main/java/com/mindmate/mindmate_server/magazine/domain/MagazineContentType.java
  src/main/java/com/mindmate/mindmate_server/magazine/domain/MagazineImage.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineContentDTO.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineContentResponse.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineCreateRequest.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineDetailResponse.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineResponse.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineUpdateRequest.java
  src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineContentRepository.java
  src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineImageRepository.java
  src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineRepositoryImpl.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineImageService.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImpl.java
  src/main/resources/static/websocket-test.html
Labels: update, feat
