Repository capstone-mindmate/mindmate-backend, pull requests merged in 2025-05, with the labels that each got.

#99 [Test, Update#94] 매거진 테스트 코드
  src/main/java/com/mindmate/mindmate_server/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ResponseTimeCalculationConsumer.java
  src/main/java/com/mindmate/mindmate_server/magazine/domain/MagazineContent.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineEngagementRequest.java
  src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineUpdateRequest.java
  src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineImageRepository.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineContentService.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazinePopularityServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineStatisticsService.java
  src/main/java/com/mindmate/mindmate_server/report/dto/ReportRequest.java
  src/main/resources/static/magazine-test.html
  src/test/java/com/mindmate/mindmate_server/emoticon/service/EmoticonServiceTest.java
  src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineContentServiceTest.java
  src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineEngagementConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineImageServiceTest.java
  src/test/java/com/mindmate/mindmate_server/magazine/service/MagazinePopularityServiceImplTest.java
  src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImplTest.java
  src/test/java/com/mindmate/mindmate_server/report/service/ReportServiceImplTest.java
Labels: refact, test

#121 [Feat#110] 인기 이모티콘 처리
  build.gradle
  src/main/java/com/mindmate/mindmate_server/chat/util/WebSocketDestinationResolver.java
  src/main/java/com/mindmate/mindmate_server/emoticon/controller/EmoticonPopularityController.java
  src/main/java/com/mindmate/mindmate_server/emoticon/domain/UserEmoticon.java
  src/main/java/com/mindmate/mindmate_server/emoticon/dto/EmoticonCount.java
  src/main/java/com/mindmate/mindmate_server/emoticon/service/EmoticonInteractionService.java
  src/main/java/com/mindmate/mindmate_server/emoticon/service/EmoticonPopularityService.java
  src/main/java/com/mindmate/mindmate_server/emoticon/service/EmoticonServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/global/util/RedisKeyManager.java
  src/main/java/com/mindmate/mindmate_server/global/util/SlackNotifier.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineContentService.java
  src/main/java/com/mindmate/mindmate_server/report/service/ReportServiceImpl.java
  src/main/resources/static/websocket-test.html
Labels: update, feat

#158 [Fix#133] 상품 등록 및 관리
  src/main/java/com/mindmate/mindmate_server/global/exception/PaymentErrorCode.java
  src/main/java/com/mindmate/mindmate_server/payment/controller/AdminProductController.java
  src/main/java/com/mindmate/mindmate_server/payment/domain/PaymentProduct.java
  src/main/java/com/mindmate/mindmate_server/payment/dto/PaymentProductRequest.java
  src/main/java/com/mindmate/mindmate_server/payment/repository/PaymentProductRepository.java
  src/main/java/com/mindmate/mindmate_server/payment/service/PaymentService.java
  src/main/java/com/mindmate/mindmate_server/payment/service/PaymentServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/review/dto/ReviewListResponse.java
  src/main/java/com/mindmate/mindmate_server/review/service/ReviewServiceImpl.java
Labels: feat

#160 [Feat#157] 카프카 장애 대응 및 프론트 기타 요구사항 해결
  build.gradle
  src/main/java/com/mindmate/mindmate_server/chat/dto/ChatRoomResponse.java
  src/main/java/com/mindmate/mindmate_server/chat/repository/ChatRoomRepositoryImpl.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ChatNotificationConsumer.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ChatRoomCloseNotificationConsumer.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ChatServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/chat/service/FilteringEventConsumer.java
  src/main/java/com/mindmate/mindmate_server/chat/service/MessageEncryptConsumer.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ResponseTimeCalculationConsumer.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ToastBoxConsumer.java
  src/main/java/com/mindmate/mindmate_server/chat/service/UnreadCountConsumer.java
  src/main/java/com/mindmate/mindmate_server/emoticon/controller/AdminEmoticonController.java
  src/main/java/com/mindmate/mindmate_server/emoticon/dto/BulkEmoticonUploadRequest.java
  src/main/java/com/mindmate/mindmate_server/emoticon/service/AdminEmoticonService.java
  src/main/java/com/mindmate/mindmate_server/global/config/KafkaConfig.java
  src/main/java/com/mindmate/mindmate_server/global/config/Resilience4JConfig.java
  src/main/java/com/mindmate/mindmate_server/global/config/WebSocketConfig.java
  src/main/java/com/mindmate/mindmate_server/global/controller/KafkaAdminController.java
  src/main/java/com/mindmate/mindmate_server/global/dto/BrokerInfoDTO.java
  src/main/java/com/mindmate/mindmate_server/global/dto/ConsumerGroupInfoDTO.java
  src/main/java/com/mindmate/mindmate_server/global/dto/DltMessageDTO.java
  src/main/java/com/mindmate/mindmate_server/global/dto/DltTopicStatusDTO.java
  src/main/java/com/mindmate/mindmate_server/global/dto/EventWrapper.java
  src/main/java/com/mindmate/mindmate_server/global/dto/KafkaDashboardDTO.java
  src/main/java/com/mindmate/mindmate_server/global/dto/KafkaHealthDTO.java
  src/main/java/com/mindmate/mindmate_server/global/service/DltMonitoringService.java
  src/main/java/com/mindmate/mindmate_server/global/service/DltReprocessingService.java
  src/main/java/com/mindmate/mindmate_server/global/service/KafkaHealthService.java
  src/main/java/com/mindmate/mindmate_server/global/service/ResilientEventPublisher.java
  src/main/java/com/mindmate/mindmate_server/global/util/GlobalDltHandler.java
  src/main/java/com/mindmate/mindmate_server/global/util/KafkaConsumerFactory.java
  src/main/java/com/mindmate/mindmate_server/global/util/KafkaStandardRetry.java
  src/main/java/com/mindmate/mindmate_server/global/util/KafkaTopicUtils.java
  src/main/java/com/mindmate/mindmate_server/global/util/SlackNotifier.java
  src/main/java/com/mindmate/mindmate_server/magazine/controller/MagazineImageController.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineEngagementConsumer.java
  src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/matching/service/MatchingEventConsumer.java
  src/main/java/com/mindmate/mindmate_server/matching/service/MatchingEventProducer.java
  src/test/java/com/mindmate/mindmate_server/chat/service/ChatNotificationConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/ChatRoomCloseNotificationConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/FilteringEventConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/MessageEncryptConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/ResponseTimeCalculationConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/ToastBoxConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/chat/service/UnreadConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineEngagementConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImplTest.java
  src/test/java/com/mindmate/mindmate_server/matching/service/MatchingEventConsumerTest.java
  src/test/java/com/mindmate/mindmate_server/matching/service/MatchingServiceImplTest.java
  src/test/java/com/mindmate/mindmate_server/payment/service/PaymentServiceImplTest.java
  src/test/java/com/mindmate/mindmate_server/point/service/PointServiceImplTest.java
  src/test/java/com/mindmate/mindmate_server/profile/service/ProfileServiceTest.java
  src/test/java/com/mindmate/mindmate_server/report/service/AdminReportServiceImplTest.java
Labels: update, feat

#162 [Feat#161] OAUTH2 적용 및 채팅방 삭제 기능
  src/main/java/com/mindmate/mindmate_server/auth/controller/AuthController.java
  src/main/java/com/mindmate/mindmate_server/auth/domain/AuthProvider.java
  src/main/java/com/mindmate/mindmate_server/auth/dto/GoogleOAuth2UserInfo.java
  src/main/java/com/mindmate/mindmate_server/auth/dto/LoginRequest.java
  src/main/java/com/mindmate/mindmate_server/auth/dto/LoginResponse.java
  src/main/java/com/mindmate/mindmate_server/auth/dto/SignUpRequest.java
  src/main/java/com/mindmate/mindmate_server/auth/service/AuthService.java
  src/main/java/com/mindmate/mindmate_server/auth/service/AuthServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/auth/service/OAuth2UserService.java
  src/main/java/com/mindmate/mindmate_server/auth/util/JwtAuthenticationFilter.java
  src/main/java/com/mindmate/mindmate_server/auth/util/JwtTokenProvider.java
  src/main/java/com/mindmate/mindmate_server/auth/util/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/mindmate/mindmate_server/auth/util/PasswordValidator.java
  src/main/java/com/mindmate/mindmate_server/chat/controller/ChatController.java
  src/main/java/com/mindmate/mindmate_server/chat/domain/ChatRoom.java
  src/main/java/com/mindmate/mindmate_server/chat/domain/UserPrincipal.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/ChatMessageResponse.java
  src/main/java/com/mindmate/mindmate_server/chat/dto/ChatRoomDetailResponse.java
  src/main/java/com/mindmate/mindmate_server/chat/repository/ChatRoomRepositoryImpl.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ChatRoomService.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/chat/service/ChatServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/global/config/SecurityConfig.java
  src/main/java/com/mindmate/mindmate_server/global/config/WebSocketConfig.java
  src/main/java/com/mindmate/mindmate_server/global/exception/AuthErrorCode.java
  src/main/java/com/mindmate/mindmate_server/global/exception/ChatErrorCode.java
  src/main/java/com/mindmate/mindmate_server/global/util/RateLimitFilter.java
  src/main/java/com/mindmate/mindmate_server/user/domain/Profile.java
  src/main/java/com/mindmate/mindmate_server/user/domain/User.java
  src/main/java/com/mindmate/mindmate_server/user/dto/ProfileCreateRequest.java
  src/main/java/com/mindmate/mindmate_server/user/repository/UserRepository.java
  src/main/java/com/mindmate/mindmate_server/user/service/ProfileServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/user/service/UserService.java
  src/main/java/com/mindmate/mindmate_server/user/service/UserServiceImpl.java
Labels: update, feat
