Repository capstone-mindmate/mindmate-backend, pull requests merged in 2025-02, with the labels that each got.

#2 Feat#1 기초 user 엔티티 및 리스너 엔티티 추가
  src/main/java/com/mindmate/mindmate_server/user/domain/CounselingField.java
  src/main/java/com/mindmate/mindmate_server/user/domain/CounselingStyle.java
  src/main/java/com/mindmate/mindmate_server/user/domain/ListenerCounselingField.java
  src/main/java/com/mindmate/mindmate_server/user/domain/ListenerProfile.java
  src/main/java/com/mindmate/mindmate_server/user/domain/RoleType.java
  src/main/java/com/mindmate/mindmate_server/user/domain/User.java
Labels: feat

#3 Feat#1 스피커 엔티티 및 글로벌 예외 처리 추가
  src/main/java/com/mindmate/mindmate_server/global/config/JpaConfig.java
  src/main/java/com/mindmate/mindmate_server/global/entity/BaseTimeEntity.java
  src/main/java/com/mindmate/mindmate_server/global/exception/CommonErrorCode.java
  src/main/java/com/mindmate/mindmate_server/global/exception/CustomException.java
  src/main/java/com/mindmate/mindmate_server/global/exception/ErrorCode.java
  src/main/java/com/mindmate/mindmate_server/global/exception/ErrorResponse.java
  src/main/java/com/mindmate/mindmate_server/global/exception/GlobalExceptionHandler.java
  src/main/java/com/mindmate/mindmate_server/user/domain/ListenerProfile.java
  src/main/java/com/mindmate/mindmate_server/user/domain/SpeakerProfile.java
  src/main/java/com/mindmate/mindmate_server/user/domain/User.java
Labels: update, feat

#6 Feat#4 로그인/회원가입/프로필 등록 with JWT
  build.gradle
  src/main/java/com/mindmate/mindmate_server/auth/controller/AuthController.java
  src/main/java/com/mindmate/mindmate_server/auth/dto/LoginRequest.java
  src/main/java/com/mindmate/mindmate_server/auth/dto/LoginResponse.java
  src/main/java/com/mindmate/mindmate_server/auth/dto/SignUpRequest.java
  src/main/java/com/mindmate/mindmate_server/auth/dto/TokenData.java
  src/main/java/com/mindmate/mindmate_server/auth/dto/TokenResponse.java
  src/main/java/com/mindmate/mindmate_server/auth/service/AuthService.java
  src/main/java/com/mindmate/mindmate_server/auth/service/AuthServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/auth/service/EmailService.java
  src/main/java/com/mindmate/mindmate_server/auth/service/LoginAttemptService.java
  src/main/java/com/mindmate/mindmate_server/auth/service/TokenService.java
  src/main/java/com/mindmate/mindmate_server/auth/util/JwtAuthenticationFilter.java
  src/main/java/com/mindmate/mindmate_server/auth/util/JwtTokenProvider.java
  src/main/java/com/mindmate/mindmate_server/auth/util/PasswordValidator.java
  src/main/java/com/mindmate/mindmate_server/auth/util/SecurityUtil.java
  src/main/java/com/mindmate/mindmate_server/global/config/RedisConfig.java
  src/main/java/com/mindmate/mindmate_server/global/config/SecurityConfig.java
  src/main/java/com/mindmate/mindmate_server/global/exception/AuthErrorCode.java
  src/main/java/com/mindmate/mindmate_server/global/exception/CommonErrorCode.java
  src/main/java/com/mindmate/mindmate_server/global/exception/CustomException.java
  src/main/java/com/mindmate/mindmate_server/global/exception/ErrorCode.java
  src/main/java/com/mindmate/mindmate_server/global/exception/ErrorResponse.java
  src/main/java/com/mindmate/mindmate_server/global/exception/GlobalExceptionHandler.java
  src/main/java/com/mindmate/mindmate_server/global/exception/ProfileErrorCode.java
  src/main/java/com/mindmate/mindmate_server/global/exception/UserErrorCode.java
  src/main/java/com/mindmate/mindmate_server/user/controller/ProfileController.java
  src/main/java/com/mindmate/mindmate_server/user/domain/ListenerProfile.java
  src/main/java/com/mindmate/mindmate_server/user/domain/RoleType.java
  src/main/java/com/mindmate/mindmate_server/user/domain/SpeakerProfile.java
  src/main/java/com/mindmate/mindmate_server/user/domain/User.java
  src/main/java/com/mindmate/mindmate_server/user/dto/CounselingResponse.java
  src/main/java/com/mindmate/mindmate_server/user/dto/ListenerProfileRequest.java
  src/main/java/com/mindmate/mindmate_server/user/dto/ProfileResponse.java
  src/main/java/com/mindmate/mindmate_server/user/dto/ProfileStatusResponse.java
  src/main/java/com/mindmate/mindmate_server/user/dto/SpeakerProfileRequest.java
  src/main/java/com/mindmate/mindmate_server/user/repository/ListenerRepository.java
  src/main/java/com/mindmate/mindmate_server/user/repository/SpeakerRepository.java
  src/main/java/com/mindmate/mindmate_server/user/repository/UserRepository.java
  src/main/java/com/mindmate/mindmate_server/user/service/ProfileService.java
  src/main/java/com/mindmate/mindmate_server/user/service/ProfileServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/user/service/UserService.java
  src/main/java/com/mindmate/mindmate_server/user/service/UserServiceImpl.java
Labels: fix, update, feat, chore

#9 Test, Refact, Update#7 auth/profile 테스트 코드 및 리팩토링
  build.gradle
  src/main/java/com/mindmate/mindmate_server/auth/controller/AuthController.java
  src/main/java/com/mindmate/mindmate_server/auth/dto/LoginRequest.java
  src/main/java/com/mindmate/mindmate_server/auth/service/AuthService.java
  src/main/java/com/mindmate/mindmate_server/auth/service/AuthServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/auth/service/EmailService.java
  src/main/java/com/mindmate/mindmate_server/auth/service/LoginAttemptService.java
  src/main/java/com/mindmate/mindmate_server/auth/service/TokenService.java
  src/main/java/com/mindmate/mindmate_server/auth/util/JwtAuthenticationFilter.java
  src/main/java/com/mindmate/mindmate_server/auth/util/JwtTokenProvider.java
  src/main/java/com/mindmate/mindmate_server/auth/util/PasswordValidator.java
  src/main/java/com/mindmate/mindmate_server/auth/util/SecurityUtil.java
  src/main/java/com/mindmate/mindmate_server/global/config/AsyncConfig.java
  src/main/java/com/mindmate/mindmate_server/global/config/SecurityConfig.java
  src/main/java/com/mindmate/mindmate_server/global/exception/AuthErrorCode.java
  src/main/java/com/mindmate/mindmate_server/global/exception/ProfileErrorCode.java
  src/main/java/com/mindmate/mindmate_server/user/controller/ProfileController.java
  src/main/java/com/mindmate/mindmate_server/user/domain/ListenerProfile.java
  src/main/java/com/mindmate/mindmate_server/user/domain/SpeakerProfile.java
  src/main/java/com/mindmate/mindmate_server/user/domain/User.java
  src/main/java/com/mindmate/mindmate_server/user/dto/ProfileResponse.java
  src/main/java/com/mindmate/mindmate_server/user/dto/ProfileStatusResponse.java
  src/main/java/com/mindmate/mindmate_server/user/service/ProfileServiceImpl.java
  src/test/java/com/mindmate/mindmate_server/auth/service/AuthServiceTest.java
  src/test/java/com/mindmate/mindmate_server/auth/service/EmailServiceTest.java
  src/test/java/com/mindmate/mindmate_server/auth/service/LoginAttemptServiceTest.java
  src/test/java/com/mindmate/mindmate_server/auth/service/TokenServiceTest.java
  src/test/java/com/mindmate/mindmate_server/profile/service/ProfileServiceTest.java
  src/test/java/com/mindmate/mindmate_server/user/service/UserServiceTest.java
Labels: update, refact, test, comment

#10 [Feat #5] 프로필 관리 및 인증 시스템
  build.gradle
  src/main/java/com/mindmate/mindmate_server/auth/util/SecurityUtil.java
  src/main/java/com/mindmate/mindmate_server/global/exception/ProfileErrorCode.java
  src/main/java/com/mindmate/mindmate_server/review/domain/Review.java
  src/main/java/com/mindmate/mindmate_server/review/dto/ReviewResponse.java
  src/main/java/com/mindmate/mindmate_server/review/repository/ReviewRepository.java
  src/main/java/com/mindmate/mindmate_server/user/controller/AdminCertificationController.java
  src/main/java/com/mindmate/mindmate_server/user/controller/ProfileController.java
  src/main/java/com/mindmate/mindmate_server/user/domain/Badge.java
  src/main/java/com/mindmate/mindmate_server/user/domain/ListenerProfile.java
  src/main/java/com/mindmate/mindmate_server/user/domain/SpeakerProfile.java
  src/main/java/com/mindmate/mindmate_server/user/dto/AdminCertificationListResponse.java
  src/main/java/com/mindmate/mindmate_server/user/dto/AdminCertificationResponse.java
  src/main/java/com/mindmate/mindmate_server/user/dto/BadgeResponse.java
  src/main/java/com/mindmate/mindmate_server/user/dto/BaseProfileResponse.java
  src/main/java/com/mindmate/mindmate_server/user/dto/CertificationProcessRequest.java
  src/main/java/com/mindmate/mindmate_server/user/dto/CertificationUpdateRequest.java
  src/main/java/com/mindmate/mindmate_server/user/dto/ListenerProfileResponse.java
  src/main/java/com/mindmate/mindmate_server/user/dto/ListenerProfileUpdateRequest.java
  src/main/java/com/mindmate/mindmate_server/user/dto/SpeakerProfileResponse.java
  src/main/java/com/mindmate/mindmate_server/user/dto/SpeakerProfileUpdateRequest.java
  src/main/java/com/mindmate/mindmate_server/user/repository/ListenerRepository.java
  src/main/java/com/mindmate/mindmate_server/user/repository/SpeakerRepository.java
  src/main/java/com/mindmate/mindmate_server/user/service/CertificationService.java
  src/main/java/com/mindmate/mindmate_server/user/service/CertificationServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/user/service/ProfileService.java
  src/main/java/com/mindmate/mindmate_server/user/service/ProfileServiceImpl.java
  src/main/java/com/mindmate/mindmate_server/user/service/UserService.java
  src/main/java/com/mindmate/mindmate_server/user/service/UserServiceImpl.java
Labels: update, feat
